[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.10.7"
serde = { version = "1.0.152", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
async-graphql = { version = "5.0.5", features = ["uuid", "uuid08"] }
