version: '3'

dotenv: ['.env']

includes:
  client:
    taskfile: ./packages/client
    dir: ./packages/client
  server:
    taskfile: ./packages/server
    dir: ./packages/server

tasks:
  author:
    desc: display author
    cmds:
      - echo 'Romain BELLANDE'

  cert:
    desc: install certificates
    cmds:
      - mkcert -install
      - mkcert -cert-file traefik/certs/local-cert.pem -key-file traefik/certs/local-key.pem "kune.localhost" "*.kune.localhost"

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: server:fix:all
      - task: client:fix:all
