[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql-axum = "5.0.5"
axum = { version = "0.6.4", features = ["ws", "headers"] }
axum-macros = "0.3.2"
chrono = "0.4.23"
http = "0.2.8"
http-body = "0.4.5"
once_cell = "1.17.0"
sea-orm = { version = "0.10.7", features = ["sqlx-postgres", "runtime-tokio-native-tls", "postgres-array"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["full"] }

[workspace]

members = [
  "./",
]

default-members = ["./"]
