version: '3'

env:
  RUST_ENV: development

tasks:
  start:
    desc: start server
    cmds:
      - cargo run
    sources:
      - ./src/**/*.rs
      - ./core/**/*.rs
      - ./entity/**/*.rs
      - ./migration/**/*.rs

  start:watch:
    desc: start server and watch
    cmds:
      - cargo watch -x run
    deps:
      - task: prisma:gen

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo fmt --all

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix

  prisma:gen:
    desc: generate prisma client
    dir: ./core
    cmds:
      - cargo prisma generate
