version: '3'

env:
  RUST_ENV: development

tasks:
  install:deps:
    desc: install dependencies
    cmds:
      - cargo install systemfd
      - cargo install cargo-watch

  start:
    desc: start server
    cmds:
      - systemfd --no-pid -s http::8083 -- cargo watch -x run

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo fmt --all

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix
