version: '3'

env:
  RUST_ENV: development

tasks:
  install:deps:
    desc: install dependencies
    cmds:
      - cargo install systemfd
      - cargo install cargo-watch
      - cargo install sea-orm-cli

  start:
    desc: start server
    cmds:
      - cargo run
    sources:
      - ./src/**/*.rs
      - ./core/**/*.rs
      - ./entity/**/*.rs
      - ./migration/**/*.rs

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo fmt --all

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix

  prisma:gen:
    desc: generate prisma client
    dir: ./core
    cmds:
      - cargo prisma generate
