version: '3'

env:
  RUST_ENV: development

tasks:
  start:
    desc: start server
    cmds:
      - cargo watch -x run

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo fmt --all

  fix:all:
    desc: fill format and lint issues when it is possible
    cmds:
      - task: format
      - task: lint:fix
